#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (coverage run --omit=./src/command_parser/*,./src/Features/Feature.py,./src/command/Command.py --branch -m nose2 test || true) && coverage html && cd htmlcov/ && python -m http.server
